- hosts: localhost
  pre_tasks:
    - name: Update xbps
      become: true
      xbps: 
        update_cache: true
        state: present
  tasks:
    # - include: tasks/core.yml
    - include: tasks/utilities.yml
    - include: tasks/js.yml
    - include: tasks/go.yml
    - include: tasks/services.yml
    - include: tasks/ssh.yml
    - include: tasks/git.yml
    - include: tasks/dotfiles.yml
