- name: install stow
  xbps: name=stow

- name: clone dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:modisek/dotfiles.git'
    dest: "{{ lookup('env', 'HOME')}}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master

- name: stow the files
  shell:  $HOME/dotfiles/setup.sh

